config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  
  devise_scope :user do
    get "/signin" => "devise/sessions#new"
    delete 'signout' => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
  end

  root 'pages#home'
  get  'about' => 'pages#about' 
  get  'contact' => 'pages#contact-us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to Online Catering</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "Online Catering", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          <% if user_signed_in? %>
          <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
          <li class="nav-item pull-md-right"><%= link_to "Sign up", signup_path,  class: "nav-link" %></li>
          <li class="nav-item pull-md-right"><%= link_to "Sign in", signin_path,  class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <%flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>
      
    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact-us.html.erb
<h1>you can contact us here</h1>
<p>email : suman@clevercoders.io</p>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to online Catering</h1>
        <p>You need food for a party, a wedding, a meeting or just for friends stopping by. We’ve put together tasty menus from premiere caterers with options that include gluten-free, celiac and halal. Your food arrives at your door, when you need it, so you can skip the stress and enjoy the party.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
 
    </div>


</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Convenience</h2>
            <p>You choose the perfect menu for your event. We deliver it on time – guaranteed. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Quality</h2>
            <p>Our caterers use the finest fresh local ingredients to create food you’ll love. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Affordability</h2>
            <p>Events don’t have to break the bank. Choose a menu for any budget. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>
   